package dart_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/rios0rios0/autoupdate/internal/domain/entities"
	dartUpdater "github.com/rios0rios0/autoupdate/internal/infrastructure/repositories/dart"
	"github.com/rios0rios0/autoupdate/test/infrastructure/gitrepo"
)

// pubspecLock is a pubspec.lock in the shape pub writes: a direct dependency,
// a direct dev dependency, a transitive one and a package the SDK provides.
const pubspecLock = `# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: "abc"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.0"
  lints:
    dependency: "direct dev"
    description:
      name: lints
      url: "https://pub.dev"
    source: hosted
    version: "3.0.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dev"
    source: hosted
    version: "4.0.2"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
sdks:
  dart: ">=3.2.0 <4.0.0"
`

// pubspec constrains packages by version strings, and one by an SDK mapping.
const pubspec = `name: example
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^3.0.0
`

func TestLockedDirectVersions(t *testing.T) {
	t.Parallel()

	t.Run("should read the packages the pubspec names, not the SDK's or transitive ones", func(t *testing.T) {
		t.Parallel()

		// given / when
		versions, err := dartUpdater.LockedDirectVersions([]byte(pubspecLock))

		// then
		require.NoError(t, err)
		assert.Equal(t, map[string]string{"http": "1.1.0", "lints": "3.0.0"}, versions)
	})

	t.Run("should fail on a lock it cannot parse", func(t *testing.T) {
		t.Parallel()

		// given / when
		versions, err := dartUpdater.LockedDirectVersions([]byte("packages: [unterminated"))

		// then
		require.Error(t, err)
		assert.Nil(t, versions)
	})
}

func TestDeclaredConstraints(t *testing.T) {
	t.Parallel()

	t.Run("should read the constraints given as version strings", func(t *testing.T) {
		t.Parallel()

		// given / when
		constraints, err := dartUpdater.DeclaredConstraints([]byte(pubspec))

		// then
		require.NoError(t, err)
		assert.Equal(t, map[string]string{"http": "^1.1.0", "lints": "^3.0.0"}, constraints)
	})
}

func TestObservePackageChanges(t *testing.T) {
	t.Parallel()

	t.Run("should report the versions the lock moved and the Flutter SDK pin", func(t *testing.T) {
		t.Parallel()

		// given
		root := gitrepo.New(t, map[string]string{
			"pubspec.lock": pubspecLock,
			"pubspec.yaml": pubspec,
			".fvmrc":       `{"flutter": "3.24.0"}`,
		})
		gitrepo.Write(t, root, map[string]string{
			"pubspec.lock": strings.NewReplacer(`"1.1.0"`, `"1.2.2"`, `"4.0.2"`, `"4.1.0"`).Replace(pubspecLock),
			"pubspec.yaml": strings.Replace(pubspec, "http: ^1.1.0", "http: ^1.2.2", 1),
			".fvmrc":       `{"flutter": "3.27.1"}`,
		})

		// when
		changes, err := dartUpdater.ObservePackageChanges(t.Context(), root)

		// then: the pubspec moved too, but the lock holds what was resolved
		require.NoError(t, err)
		assert.ElementsMatch(t, []entities.DependencyChange{
			{Subject: entities.SubjectDartPackage, Name: "http", From: "1.1.0", To: "1.2.2"},
			{Subject: entities.SubjectFlutterVersion, From: "3.24.0", To: "3.27.1"},
		}, changes)
	})

	t.Run("should read the constraints of a package whose lock is not committed", func(t *testing.T) {
		t.Parallel()

		// given
		root := gitrepo.New(t, map[string]string{"pubspec.yaml": pubspec})
		gitrepo.Write(t, root, map[string]string{
			"pubspec.yaml": strings.Replace(pubspec, "lints: ^3.0.0", "lints: ^5.0.0", 1),
			"pubspec.lock": pubspecLock,
		})

		// when
		changes, err := dartUpdater.ObservePackageChanges(t.Context(), root)

		// then
		require.NoError(t, err)
		assert.Equal(t, []entities.DependencyChange{
			{Subject: entities.SubjectDartPackage, Name: "lints", From: "^3.0.0", To: "^5.0.0"},
		}, changes)
	})

	t.Run("should fail on a lock it cannot parse", func(t *testing.T) {
		t.Parallel()

		// given
		root := gitrepo.New(t, map[string]string{"pubspec.lock": pubspecLock})
		gitrepo.Write(t, root, map[string]string{"pubspec.lock": "packages: [unterminated"})

		// when
		changes, err := dartUpdater.ObservePackageChanges(t.Context(), root)

		// then
		require.Error(t, err)
		assert.Nil(t, changes)
	})
}
