package python_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/rios0rios0/autoupdate/internal/domain/entities"
	pyUpdater "github.com/rios0rios0/autoupdate/internal/infrastructure/repositories/python"
	"github.com/rios0rios0/autoupdate/test/infrastructure/gitrepo"
)

// pdmLock is a pdm.lock in the shape PDM writes, resolving a declared package
// and the transitive one it pulls in.
const pdmLock = `# This file is @generated by PDM.
# It is not intended for manual editing.

[metadata]
groups = ["default"]
strategy = ["inherit_metadata"]
lock_version = "4.5.0"
content_hash = "sha256:0123"

[[package]]
name = "requests"
version = "2.31.0"
requires_python = ">=3.7"
summary = "Python HTTP for Humans."
groups = ["default"]
dependencies = [
    "charset-normalizer<4,>=2",
    "urllib3<3,>=1.21.1",
]
files = [
    {file = "requests-2.31.0-py3-none-any.whl", hash = "sha256:abc"},
]

[[package]]
name = "urllib3"
version = "2.0.7"
requires_python = ">=3.7"
summary = "HTTP library."
groups = ["default"]
`

// pyproject declares requests directly, and urllib3 only through it.
const pyproject = `[project]
name = "example"
version = "1.0.0"
requires-python = ">=3.12"
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "requests>=2.31",
]

[dependency-groups]
dev = ["pytest>=8.0"]
`

func TestRequirementPins(t *testing.T) {
	t.Parallel()

	t.Run("should read exact pins and nothing else", func(t *testing.T) {
		t.Parallel()

		// given
		content := "# generated by pip freeze\r\n" +
			"Django==5.0.1\r\n" +
			"requests[security]==2.31.0 ; python_version >= \"3.8\"\n" +
			"urllib3===2.0.7 \\\n    --hash=sha256:abc \\\n    --hash=sha256:def\n" +
			"flask>=3.0\n" +
			"-r base.txt\n" +
			"-e git+https://github.com/org/pkg.git#egg=pkg\n" +
			"pkg @ https://example.com/pkg.whl\n" +
			"celery==5.*\n" +
			"   # an indented comment\n"

		// when
		pins := pyUpdater.RequirementPins([]byte(content))

		// then
		assert.Equal(t, map[string]string{
			"Django":   "5.0.1",
			"requests": "2.31.0",
			"urllib3":  "2.0.7",
		}, pins)
	})
}

func TestPdmLockVersions(t *testing.T) {
	t.Parallel()

	t.Run("should read every package the lock resolves", func(t *testing.T) {
		t.Parallel()

		// given / when
		versions, err := pyUpdater.PdmLockVersions([]byte(pdmLock))

		// then
		require.NoError(t, err)
		assert.Equal(t, map[string]string{"requests": "2.31.0", "urllib3": "2.0.7"}, versions)
	})

	t.Run("should read a lock without packages as empty", func(t *testing.T) {
		t.Parallel()

		// given
		lock := "[metadata]\ngroups = [\"default\"]\n"

		// when
		versions, err := pyUpdater.PdmLockVersions([]byte(lock))

		// then
		require.NoError(t, err)
		assert.Empty(t, versions)
	})

	t.Run("should fail on packages it cannot read", func(t *testing.T) {
		t.Parallel()

		// given: a future shape that moved the keys out of the table
		lock := "[[package]]\n  name = \"requests\"\n  version = \"2.31.0\"\n"

		// when
		versions, err := pyUpdater.PdmLockVersions([]byte(lock))

		// then
		require.Error(t, err)
		assert.Nil(t, versions)
	})
}

func TestDeclaredRequirementNames(t *testing.T) {
	t.Parallel()

	t.Run("should read the requirements a pyproject declares", func(t *testing.T) {
		t.Parallel()

		// given / when
		names := pyUpdater.DeclaredRequirementNames([]byte(pyproject))

		// then: the project's own name is quoted too, which is harmless, since
		// the names only ever filter what a lock resolved
		assert.Contains(t, names, "requests")
		assert.Contains(t, names, "pytest")
		assert.NotContains(t, names, "urllib3")
		assert.NotContains(t, names, "Programming")
	})
}

func TestObservePackageChanges(t *testing.T) {
	t.Parallel()

	t.Run("should report the pins and the Python version a pip run moved", func(t *testing.T) {
		t.Parallel()

		// given
		root := gitrepo.New(t, map[string]string{
			"requirements.txt": "Django==5.0.1\nrequests==2.31.0\nidna==3.6\n",
			".python-version":  "3.12.1\n",
		})
		gitrepo.Write(t, root, map[string]string{
			"requirements.txt": "Django==5.0.2\nrequests==2.32.3\nidna==3.6\ncertifi==2024.2.2\n",
			".python-version":  "3.13.1\n",
		})

		// when
		changes, err := pyUpdater.ObservePackageChanges(t.Context(), root)

		// then
		require.NoError(t, err)
		assert.ElementsMatch(t, []entities.DependencyChange{
			{Subject: entities.SubjectPythonPackage, Name: "Django", From: "5.0.1", To: "5.0.2"},
			{Subject: entities.SubjectPythonPackage, Name: "requests", From: "2.31.0", To: "2.32.3"},
			{Subject: entities.SubjectPythonVersion, From: "3.12.1", To: "3.13.1"},
		}, changes)
	})

	t.Run("should report only the packages a PDM project declares", func(t *testing.T) {
		t.Parallel()

		// given
		root := gitrepo.New(t, map[string]string{"pdm.lock": pdmLock, "pyproject.toml": pyproject})
		upgraded := strings.NewReplacer(
			`version = "2.31.0"`, `version = "2.32.3"`,
			`version = "2.0.7"`, `version = "2.2.2"`,
		).Replace(pdmLock)
		gitrepo.Write(t, root, map[string]string{"pdm.lock": upgraded})

		// when
		changes, err := pyUpdater.ObservePackageChanges(t.Context(), root)

		// then: urllib3 moved too, but only because requests needs it
		require.NoError(t, err)
		assert.Equal(t, []entities.DependencyChange{
			{Subject: entities.SubjectPythonPackage, Name: "requests", From: "2.31.0", To: "2.32.3"},
		}, changes)
	})

	t.Run("should fail on a pdm.lock it cannot read", func(t *testing.T) {
		t.Parallel()

		// given
		root := gitrepo.New(t, map[string]string{"pdm.lock": pdmLock, "pyproject.toml": pyproject})
		gitrepo.Write(t, root, map[string]string{"pdm.lock": "[[package]]\n  name = \"requests\"\n"})

		// when
		changes, err := pyUpdater.ObservePackageChanges(t.Context(), root)

		// then
		require.Error(t, err)
		assert.Nil(t, changes)
	})
}
