package javascript_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/rios0rios0/autoupdate/internal/domain/entities"
	"github.com/rios0rios0/autoupdate/internal/infrastructure/repositories/javascript"
	"github.com/rios0rios0/autoupdate/test/infrastructure/gitrepo"
)

// rootManifest declares a dependency, a dev dependency and a workspace link.
const rootManifest = `{
  "name": "example",
  "version": "1.0.0",
  "dependencies": {"react": "^18.2.0", "internal": "workspace:*"},
  "devDependencies": {"typescript": "~5.4.0"}
}`

// packageLockV3 resolves the root's packages, a transitive one, and a copy of
// react nested under a workspace.
const packageLockV3 = `{
  "name": "example",
  "lockfileVersion": 3,
  "packages": {
    "": {"name": "example", "version": "1.0.0"},
    "node_modules/react": {"version": "18.2.0"},
    "node_modules/typescript": {"version": "5.4.2"},
    "node_modules/loose-envify": {"version": "1.4.0"},
    "packages/web/node_modules/react": {"version": "17.0.2"}
  }
}`

// pnpmLockV9 files the root project under "importers", with a peer suffix on
// one version and a linked workspace dependency.
const pnpmLockV9 = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

importers:

  .:
    dependencies:
      react:
        specifier: ^18.2.0
        version: 18.2.0
      react-dom:
        specifier: ^18.2.0
        version: 18.2.0(react@18.2.0)
      internal:
        specifier: workspace:*
        version: link:packages/internal
    devDependencies:
      typescript:
        specifier: ~5.4.0
        version: 5.4.2

packages:

  react@18.2.0:
    resolution: {integrity: sha512-abc}
`

// yarnClassicLock lists an entry satisfying two descriptors.
const yarnClassicLock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"react@^18.0.0", "react@^18.2.0":
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"
  dependencies:
    loose-envify "^1.1.0"

typescript@~5.4.0:
  version "5.4.2"
`

// yarnBerryLock spells registry descriptors with the npm: protocol.
const yarnBerryLock = `__metadata:
  version: 8
  cacheKey: 10c0

"react@npm:^18.0.0, react@npm:^18.2.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"
  dependencies:
    loose-envify: "npm:^1.1.0"
  languageName: node
  linkType: hard

"typescript@npm:~5.4.0":
  version: 5.4.2
  resolution: "typescript@npm:5.4.2"
`

// declared is what rootManifest declares from the registry.
func declared() map[string]string {
	return map[string]string{"react": "^18.2.0", "typescript": "~5.4.0"}
}

func TestDeclaredRanges(t *testing.T) {
	t.Parallel()

	t.Run("should read registry dependencies and skip links, paths and repositories", func(t *testing.T) {
		t.Parallel()

		// given
		manifest := `{
  "dependencies": {"react": "^18.2.0", "internal": "workspace:*", "local": "file:../local"},
  "devDependencies": {"typescript": "~5.4.0", "fork": "github:org/fork", "git": "git+https://x/y.git"},
  "optionalDependencies": {"fsevents": "2.3.3"},
  "peerDependencies": {"react-dom": "^18.0.0"}
}`

		// when
		ranges, err := javascript.DeclaredRanges([]byte(manifest))

		// then
		require.NoError(t, err)
		assert.Equal(t, map[string]string{"react": "^18.2.0", "typescript": "~5.4.0", "fsevents": "2.3.3"}, ranges)
	})
}

func TestResolveLockfile(t *testing.T) {
	t.Parallel()

	t.Run("should resolve every lockfile shape to the versions it locks", func(t *testing.T) {
		t.Parallel()

		testCases := []struct {
			name string
			file string
			lock string
			dir  string
			want map[string]string
		}{
			{
				name: "package-lock v3, root",
				file: "package-lock.json", lock: packageLockV3, dir: ".",
				want: map[string]string{"react": "18.2.0", "typescript": "5.4.2"},
			},
			{
				name: "package-lock v3, a workspace's own copy",
				file: "package-lock.json", lock: packageLockV3, dir: "packages/web",
				want: map[string]string{"react": "17.0.2", "typescript": "5.4.2"},
			},
			{
				name: "package-lock v1",
				file: "package-lock.json",
				lock: `{"lockfileVersion": 1, "dependencies": {"react": {"version": "18.2.0"}}}`,
				dir:  ".",
				want: map[string]string{"react": "18.2.0"},
			},
			{
				name: "pnpm v9",
				file: "pnpm-lock.yaml", lock: pnpmLockV9, dir: ".",
				want: map[string]string{"react": "18.2.0", "typescript": "5.4.2"},
			},
			{
				name: "pnpm v5",
				file: "pnpm-lock.yaml",
				lock: "lockfileVersion: 5.4\n\nspecifiers:\n  react: ^18.2.0\n\n" +
					"dependencies:\n  react: 18.2.0_react-dom@18.2.0\n\ndevDependencies:\n  typescript: 5.4.2\n",
				dir:  ".",
				want: map[string]string{"react": "18.2.0", "typescript": "5.4.2"},
			},
			{
				name: "yarn classic",
				file: "yarn.lock", lock: yarnClassicLock, dir: ".",
				want: map[string]string{"react": "18.2.0", "typescript": "5.4.2"},
			},
			{
				name: "yarn berry",
				file: "yarn.lock", lock: yarnBerryLock, dir: ".",
				want: map[string]string{"react": "18.2.0", "typescript": "5.4.2"},
			},
		}

		for _, testCase := range testCases {
			// when
			versions, err := javascript.ResolveLockfile(testCase.file, []byte(testCase.lock), testCase.dir, declared())

			// then
			require.NoError(t, err, testCase.name)
			assert.Equal(t, testCase.want, versions, testCase.name)
		}
	})

	t.Run("should skip a dependency pnpm links rather than resolves", func(t *testing.T) {
		t.Parallel()

		// given
		withLink := map[string]string{"internal": "^1.0.0", "react-dom": "^18.2.0"}

		// when
		versions, err := javascript.ResolveLockfile("pnpm-lock.yaml", []byte(pnpmLockV9), ".", withLink)

		// then: the peer suffix is dropped, the link names no release
		require.NoError(t, err)
		assert.Equal(t, map[string]string{"react-dom": "18.2.0"}, versions)
	})

	t.Run("should fail on a lockfile whose entries it cannot read", func(t *testing.T) {
		t.Parallel()

		testCases := map[string]string{
			"package-lock.json": `{"name": "example"}`,
			"yarn.lock":         "\"react@^18.2.0\":\n  resolution \"react@18.2.0\"\n",
		}

		for file, lock := range testCases {
			// when
			versions, err := javascript.ResolveLockfile(file, []byte(lock), ".", declared())

			// then
			require.Error(t, err, file)
			assert.Nil(t, versions, file)
		}
	})
}

func TestObservePackageChanges(t *testing.T) {
	t.Parallel()

	t.Run("should report what the lockfile resolves for declared packages and the Node.js pin", func(t *testing.T) {
		t.Parallel()

		// given: npm update moved react within its range, and a transitive package
		root := gitrepo.New(t, map[string]string{
			"package.json":      rootManifest,
			"package-lock.json": packageLockV3,
			".nvmrc":            "v20.11.0\n",
			".node-version":     "20.11.0\n",
		})
		gitrepo.Write(t, root, map[string]string{
			"package-lock.json": strings.NewReplacer(
				`"node_modules/react": {"version": "18.2.0"}`, `"node_modules/react": {"version": "18.3.1"}`,
				`"1.4.0"`, `"1.5.0"`,
			).Replace(packageLockV3),
			".nvmrc":        "v22.12.0\n",
			".node-version": "22.12.0\n",
		})

		// when
		changes, err := javascript.ObservePackageChanges(t.Context(), root)

		// then: one pin per file -- the writer folds them -- and no loose-envify
		require.NoError(t, err)
		assert.ElementsMatch(t, []entities.DependencyChange{
			{Subject: entities.SubjectJavaScriptPackage, Name: "react", From: "18.2.0", To: "18.3.1"},
			{Subject: entities.SubjectNodeVersion, From: "20.11.0", To: "22.12.0"},
			{Subject: entities.SubjectNodeVersion, From: "20.11.0", To: "22.12.0"},
		}, changes)
	})

	t.Run("should follow a range the run raised to the version the lockfile resolves", func(t *testing.T) {
		t.Parallel()

		// given: pnpm update --latest rewrote the range and the lock
		root := gitrepo.New(t, map[string]string{"package.json": rootManifest, "pnpm-lock.yaml": pnpmLockV9})
		gitrepo.Write(t, root, map[string]string{
			"package.json": strings.Replace(rootManifest, `"~5.4.0"`, `"~5.6.0"`, 1),
			"pnpm-lock.yaml": strings.NewReplacer(
				"specifier: ~5.4.0", "specifier: ~5.6.0",
				"version: 5.4.2", "version: 5.6.3",
			).Replace(pnpmLockV9),
		})

		// when
		changes, err := javascript.ObservePackageChanges(t.Context(), root)

		// then
		require.NoError(t, err)
		assert.Equal(t, []entities.DependencyChange{
			{Subject: entities.SubjectJavaScriptPackage, Name: "typescript", From: "5.4.2", To: "5.6.3"},
		}, changes)
	})

	t.Run("should compare the ranges themselves when no lockfile moved", func(t *testing.T) {
		t.Parallel()

		// given
		root := gitrepo.New(t, map[string]string{"package.json": rootManifest})
		gitrepo.Write(t, root, map[string]string{
			"package.json": strings.Replace(rootManifest, `"^18.2.0"`, `"^19.0.0"`, 1),
		})

		// when
		changes, err := javascript.ObservePackageChanges(t.Context(), root)

		// then
		require.NoError(t, err)
		assert.Equal(t, []entities.DependencyChange{
			{Subject: entities.SubjectJavaScriptPackage, Name: "react", From: "18.2.0", To: "19.0.0"},
		}, changes)
	})

	t.Run("should fail on a lockfile it cannot read", func(t *testing.T) {
		t.Parallel()

		// given
		root := gitrepo.New(t, map[string]string{"package.json": rootManifest, "yarn.lock": yarnClassicLock})
		gitrepo.Write(t, root, map[string]string{"yarn.lock": "\"react@^18.2.0\":\n  resolution \"x\"\n"})

		// when
		changes, err := javascript.ObservePackageChanges(t.Context(), root)

		// then
		require.Error(t, err)
		assert.Nil(t, changes)
	})
}
