package support

// skippedWalkDirs names the directories the repository walkers never descend
// into. It is deliberately a *deny* list, and that direction is the whole point.
//
// The rule it replaces skipped every directory whose name began with a dot,
// which conflated "hidden" with "not the repository's own source".
// `.github/workflows/ci.yaml` is hidden and is very much the repository's own
// source, so the clone-based pipeline updater could never see a GitHub Actions
// workflow: `langforge`'s detector matched the repository through the provider
// API, the repository was cloned, the walk then returned nothing, and the run
// reported success with zero upgrades. Only `azure-pipelines.yml` at the root
// and `azure-devops/` were ever reachable on disk. A discovery default of
// "skip" fails exactly like that — silently, with no error to notice.
//
// An allow list of the hidden directories that matter (`.github`, `.circleci`,
// …) would reproduce that failure one CI system later: `.gitea/workflows/`,
// `.forgejo/workflows/` or `.woodpecker/` would each be invisible until somebody
// noticed, because this bug *is* a missing entry in an implicit allow list. An
// opt-in parameter or a second walker variant would be worse still — it leaves
// the blind behaviour as the default that every future caller gets for free.
// With a deny list, a forgotten entry costs a slower walk and, at worst, a match
// inside a derived tree: loud, and visible in the resulting diff.
//
// Every entry is a tree the repository does not author. `.git` is the reason the
// list exists at all: it is not merely large, it holds loose objects and
// packfiles whose names can satisfy any predicate, and callers feed these
// results straight into WriteFileChanges, which writes back under root — a match
// there would rewrite repository internals. The caches and vendored trees are
// regenerated by their own tooling, so an "upgrade" applied inside one can never
// reach the pull request, yet it would still reach the changelog and the PR
// body, making a run claim work it did not do.
//
// Editor state (`.idea`, `.vscode`) is deliberately absent: it is authored and
// committed by the repository, so excluding it would need the same
// case-by-case reasoning this list exists to avoid. Nothing upgradable lives
// there, and walking it costs a handful of small files.
var skippedWalkDirs = map[string]struct{}{ //nolint:gochecknoglobals // immutable lookup set
	// Version-control metadata.
	".git": {},
	".hg":  {},
	".svn": {},

	// Vendored third-party source. Committed or not, it belongs to another
	// project and is regenerated by `go mod vendor`, `npm install` and friends.
	"vendor":       {},
	"node_modules": {},

	// Terraform and Terragrunt download remote modules and providers here, so
	// the tree is full of `.tf`/`.hcl` files that mirror somebody else's code.
	".terraform":        {},
	".terragrunt-cache": {},

	// Python environments and tool caches.
	".venv":         {},
	"venv":          {},
	".tox":          {},
	".nox":          {},
	".eggs":         {},
	"__pycache__":   {},
	".mypy_cache":   {},
	".pytest_cache": {},
	".ruff_cache":   {},

	// JavaScript package stores and build caches.
	".yarn":         {},
	".pnpm-store":   {},
	".next":         {},
	".nuxt":         {},
	".svelte-kit":   {},
	".angular":      {},
	".turbo":        {},
	".parcel-cache": {},

	// JVM, Dart and Ruby caches.
	".gradle":    {},
	".m2":        {},
	".dart_tool": {},
	".pub-cache": {},
	".bundle":    {},

	// Generic tool cache directory.
	".cache": {},
}

// shouldSkipWalkDir reports whether a directory name belongs to a tree the
// repository does not author, and must therefore never be walked.
func shouldSkipWalkDir(name string) bool {
	_, skipped := skippedWalkDirs[name]
	return skipped
}
